
DATA_DIRECTORY: /Users/cguerner/data/dl_data
#/cluster/scratch/cguerner/dl_data
#"${SCRATCH}/dl_data" 

SPLICEAI:
  data: spliceai
  splice_table: gtex_dataset.txt
  genome: genome.fa

CHROME_GCN:
  data_dir: chrome_gcn
  chrom_sizes: orig_data/genome/hg19/hg19.chrom_sizes

DATA_PIPELINE:
  context_length: 80
  window_size: 5000 # need to integrate
  train_chroms: 
    - chr11
    - chr13
    - chr15
    - chr17
    - chr19
    - chr21
    - chr2
    - chr4
    - chr6
    - chr8
    - chr10
    - chr12,
    - chr14
    - chr16
    - chr18
    - chr20
    - chr22
    - chrX
    - chrY
  test_chroms:
    - chr1
    - chr3
    - chr5
    - chr7
    - chr9