
DATA_DIRECTORY: /cluster/scratch/cguerner/dl_data/splicing

RAW_DATA:  
  splice_table: raw_data/gtex_dataset.txt
  genome: raw_data/genome.fa
  chrom_sizes: raw_data/genome/hg19/hg19.chrom_sizes
  genome_root: raw_data/genome
  input_root: raw_data/encode
  hic_root: raw_data/hic
  expr_root: raw_data/roadmap_expression

DATA_PIPELINE:
  output_dir: processed_data
  context_length: 400
  window_size: 5000
  # max number of genes to be stored in a single h5 dataset.
  dataset_chunk_size: 2000
  train_chroms:
    - chr2
    - chr4
    - chr5
    - chr6
    - chr7
    - chr9
    - chr10
    - chr11
    - chr13
    - chr14
    - chr15
    - chr16
    - chr18
    - chr19
    - chr20
    - chr22
#    - chrX
#    - chrY
  valid_chroms:
    - chr3
    - chr12
    - chr17
  test_chroms:
    - chr1
    - chr8
    - chr21
  train_chroms_spliceai:
    - chr11
    - chr13
    - chr15
    - chr17
    - chr19
    - chr21
    - chr2
    - chr4
    - chr6
    - chr8
    - chr10
    - chr12
    - chr14
    - chr16
    - chr18
    - chr20
    - chr22
    - chrX
    - chrY
  test_chroms_spliceai:
    - chr1
    - chr3
    - chr5
    - chr7
    - chr9

TRAINING:
  results_dir: results
  test_models_dir: test_models
