
DATA_DIRECTORY: "/cluster/scratch/cguerner" 
#"${SCRATCH}" "/Users/cguerner/data/dl_data"

SPLICEAI:
  data: spliceai
  splice_table: gtex_dataset.txt
  genome: genome.fa
  sequence: gtex_sequence.txt
  cl_max: 80
  sl: 5000

CHROMEGCN:
  data_dir: chrome_gcn
  chrom_sizes: orig_data/genome/hg19/hg19.chrom_sizes