
DATA_DIRECTORY: /home/anej/repos/studies/deep-learning-project/data

SPLICEAI:
  data: spliceai
  splice_table: gtex_dataset.txt
  genome: genome.fa

CHROME_GCN:
  data_dir: chrome_gcn
  chrom_sizes: orig_data/genome/hg19/hg19.chrom_sizes

RAW_DATA:  
  splice_table: raw_data/gtex_dataset.txt
  genome: raw_data/genome.fa
  chrom_sizes: raw_data/genome/hg19/hg19.chrom_sizes
  genome_root: raw_data/genome
  input_root: raw_data/encode
  hic_root: raw_data/hic
  expr_root: raw_data/roadmap_expression

DATA_PIPELINE:
  output_dir: processed_data
  context_length: 400
  window_size: 5000 # need to integrate
  train_chroms: 
    - chr11
    - chr13
    - chr15
    - chr17
    - chr19
    - chr21
    - chr2
    - chr4
    - chr6
    - chr8
    - chr10
    - chr12
    - chr14
    - chr16
    - chr18
    - chr20
    - chr22
#    - chrX
#    - chrY
  test_chroms:
    - chr1
    - chr3
    - chr5
    - chr7
    - chr9

TRAINING:
  results_dir: results
