
DATA_DIRECTORY: /cluster/scratch/asvete/deep-learning-project/data

RAW_DATA:  
  splice_table: raw_data/gtex_dataset.txt
  genome: raw_data/genome.fa
  chrom_sizes: raw_data/genome/hg19/hg19.chrom_sizes
  genome_root: raw_data/genome
  hic_root: raw_data/hic

DATA_PIPELINE:
  output_dir: processed_data
  # max number of genes to be stored in a single h5 dataset.
  dataset_chunk_size: 2000
  train_chroms:
    - chr7
    - chr2
    - chr4
    - chr5
    - chr6
    - chr9
    - chr10
    - chr11
    - chr13
    - chr14
    - chr15
    - chr16
    - chr18
    - chr19
    - chr20
    - chr22
  valid_chroms:
    - chr3
    - chr12
    - chr17
  test_chroms:
    - chr1
    - chr8
    - chr21

TRAINING:
  results_dir: results
  test_baseline_models_dir: test_baseline_models
  test_graph_models_dir: test_graph_models
